#!/usr/bin/env python
import dacite
import requests

from datetime import datetime

from .exceptions import FDMSApiException
from .utils import device_id_request, parse_data
from .models.receipts import (
    SubmitReceipt,
    ReceiptServerSignature,
)

class ReceiptsClient:
    """Receipts API"""

    def __init__(self, client):
        self.client = client

    def submit_receipt(
        self,
        deviceID: int,
        receiptType: str,
        receiptCurrency: str,
        receiptCounter: int,
        receiptGlobalNo: int,
        invoiceNo: str,
        receiptDate: str,
        receiptLinesTaxInclusive: bool,
        receiptLines: list[dict],
        receiptTaxes: list[dict],
        receiptPayments: list[dict],
        receiptTotal: float,
        receiptDeviceSignature: dict,
        receiptPrintForm: str = "Receipt48",
        buyerData: dict | None = None,
        receiptNotes: str | None = None,
        creditDebitNote: dict | None = None,
        username: str | None = None,
        userNameSurname: str | None = None,
    ) -> SubmitReceipt:
        """
        Submit a fiscal receipt to the FDMS gateway (Online mode only).

        This method is asynchronous — FDMS acknowledges the request synchronously
        but processes and validates the receipt asynchronously.

        Receipt can only be submitted when fiscal day status is:
            - FiscalDayOpened
            - FiscalDayCloseFailed

        If the same receipt (same deviceID, receiptGlobalNo and receiptHash) is
        submitted more than once, FDMS returns the original receiptID and
        receiptServerSignature with a different operationID.

        Note: receiptNotes is mandatory when receiptType is CreditNote or DebitNote.
        Note: creditDebitNote is mandatory when receiptType is CreditNote or DebitNote.

        :param deviceID: Device identification ID.
        :type  deviceID: ``int``

        :param receiptType: Type of receipt. e.g. FiscalInvoice, CreditNote, DebitNote.
        :type  receiptType: ``str``

        :param receiptCurrency: ISO 4217 currency code e.g. "ZWG".
                                Validation: RCPT010 - must be present and valid in FDMS.
        :type  receiptCurrency: ``str`` (3)

        :param receiptCounter: Daily ascending serial number of receipt assigned by device.
                            Validation: RCPT011 - must be 1 for first receipt, then increment by 1.
        :type  receiptCounter: ``int``

        :param receiptGlobalNo: Cumulative ascending serial number since device activation.
                                Validation: RCPT012 - must be greater by 1 from previous or 1 for first receipt in day.
        :type  receiptGlobalNo: ``int``

        :param invoiceNo: Unique invoice number generated by accounting system.
                        Validation: RCPT013 - must be unique in taxpayer context.
        :type  invoiceNo: ``str`` (50)

        :param receiptDate: Local datetime when receipt was printed. No timezone.
                            Format: ISO 8601 e.g. "2026-04-29T23:02:33".
                            Validation: RCPT014, RCPT030, RCPT031, RCPT041.
        :type  receiptDate: ``str``

        :param receiptLinesTaxInclusive: True if receipt line prices include tax, False if exclusive.
        :type  receiptLinesTaxInclusive: ``bool``

        :param receiptLines: List of receipt line items. At least one required (RCPT016).
        :type  receiptLines: ``list[dict]``

        :param receiptTaxes: List of tax breakdowns. At least one required (RCPT017).
        :type  receiptTaxes: ``list[dict]``

        :param receiptPayments: List of payment methods and amounts. At least one required (RCPT018).
        :type  receiptPayments: ``list[dict]``

        :param receiptTotal: Total receipt amount in receipt currency.
                            Validation: RCPT019, RCPT037, RCPT038, RCPT039, RCPT040.
        :type  receiptTotal: ``float``

        :param receiptDeviceSignature: SHA256 hash and device private key signature of receipt.
                                    Validation: RCPT020 - must be valid.
        :type  receiptDeviceSignature: ``dict``

        :param receiptPrintForm: Format receipt was printed in. Defaults to "Receipt48".
        :type  receiptPrintForm: ``str``

        :param buyerData: Optional buyer information. If provided, buyerRegisterName
                        and buyerTIN are mandatory within it (RCPT043).
        :type  buyerData: ``dict | None``

        :param receiptNotes: Receipt notes. Mandatory for CreditNote and DebitNote (RCPT034).
        :type  receiptNotes: ``str | None``

        :param creditDebitNote: Reference to original invoice. Mandatory for CreditNote
                                and DebitNote (RCPT015). Either receiptID alone, or
                                deviceID + receiptGlobalNo + fiscalDayNo must be provided.
        :type  creditDebitNote: ``dict | None``

        :param username: Username of operator who created the invoice.
        :type  username: ``str | None`` (100)

        :param userNameSurname: Full name of operator who created the invoice.
        :type  userNameSurname: ``str | None`` (250)

        :return: A SubmitReceipt dataclass with receiptID, serverDate,
                receiptServerSignature and operationID.
        :rtype: SubmitReceipt

        :raises FDMSApiException: If the API returns a DEV or FISC error response.
        :raises FDMSValidationException: If receipt fails FDMS validation (RCPT0xx errors).
        """
        receipt = {
            "receiptType": receiptType,
            "receiptCurrency": receiptCurrency,
            "receiptCounter": receiptCounter,
            "receiptGlobalNo": receiptGlobalNo,
            "invoiceNo": invoiceNo,
            "receiptDate": receiptDate,
            "receiptLinesTaxInclusive": receiptLinesTaxInclusive,
            "receiptLines": receiptLines,
            "receiptTaxes": receiptTaxes,
            "receiptPayments": receiptPayments,
            "receiptTotal": receiptTotal,
            "receiptPrintForm": receiptPrintForm,
            "receiptDeviceSignature": receiptDeviceSignature,
        }

        if buyerData is not None:
            receipt["buyerData"] = buyerData
        if receiptNotes is not None:
            receipt["receiptNotes"] = receiptNotes
        if creditDebitNote is not None:
            receipt["creditDebitNote"] = creditDebitNote
        if username is not None:
            receipt["username"] = username
        if userNameSurname is not None:
            receipt["userNameSurname"] = userNameSurname

        response = self.client.post(
            f"{deviceID}/SubmitReceipt",
            {"receipt": receipt},
        )
        return parse_data(response, SubmitReceipt)